name: AgriAssist CI/CD Pipeline

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Tests
        working-directory: ./backend
        run: npm test

  deploy:

    needs: build-and-test

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:

      - name: Deployment
        run: echo "AgriAssist deployment successful"